services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333 # REST API + Web UI (browser me dashboard open kar sakte ho)
      - 6334:6334 # actual database ka "door" jahan se data aata jaata hai (actual db connection)
    volumes:
      - qdrant_data:/qdrant/storage

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474 # REST API + Web UI (dashboard)
      - 7687:7687 # actual database ka "door" jahan se data aata jaata hai (actual db connection)
    environment:
      NEO4J_AUTH: neo4j/reform-william-center-vibrate-press-5829 #username(fixed)/password
      NEO4J_PLUGINS: '["apoc"]' 
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,apoc.meta.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,apoc.meta.*'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
    volumes:
      - neo4j_data:/data

volumes:
  qdrant_data:
  neo4j_data: