from fastapi import FastAPI, UploadFile
from .utils.file import save_to_disk
from .db.collections.files import files_collection, FileSchema

app = FastAPI()


@app.get("/")
def hello():
    return {"status": "healthy"}


@app.post("/upload")
async def upload_file(file: UploadFile):

    db_file = await files_collection.insert_one(
        document=FileSchema(
            name=file.filename,
            status="saving"
        ).model_dump()  # converts to dict
    )
    # db_file.inserted_id = id generated by mongodb for each obj
    file_path = f"/mnt/uploads/{str(db_file.inserted_id)}/{file.filename}"

    await save_to_disk(file=await file.read(), path=file_path)

    # Push to Queue
    print("queued")

    # MongoDB (update status uploded)
    await files_collection.update_one({"_id": db_file.inserted_id}, {
        "$set": {
            "status": "queued"
        }
    })

    return {"file_id": str(db_file.inserted_id)}
